### ISSUE TITLE
Access violation after closing pas file if new active file is a form

### ISSUE THREAD

**Issue by BvdLind** [AntoineGS/Vi4D#1]
First of all thank you for improving on the abandoned vi plugin. It works much better than the previous one already.

I just found a bug that I was able to reproduce and that I wanted to share.

I have the below situation:
<img width="1149" alt="Screenshot 2024-12-06 at 10 07 03" src="https://github.com/user-attachments/assets/f6fcc2fa-2989-4a92-a700-596c45c9ca2a">

So I have a regular .pas file open. If I then click to close the tab Delphi will open temp2frm (a form) in design view and I get

<img width="830" alt="Screenshot 2024-12-06 at 09 57 16" src="https://github.com/user-attachments/assets/b475bead-0bf7-49e6-8beb-32ebf6b16236">

Makes sense that it can't configure the cursor when we're in design view. There are some other situations in which this happens which can happen pretty frequently, but these are less easily reproduced.

**Comment by AntoineGS** [comment]
I never though I would be this happy seeing an issue 🤣, I really did not think anyone would end up using it (apart from me).
Thank you for the report!

I will look into this, I have never used that close button, right-clicking and choosing Close Page does not cause this issue (or using :q) which is what I usually do.

The right fix might take me some time to find, the APIs are not well documented, in the meantime you could comment this out:
```
procedure TEngine.LButtonDown;
begin
  FCurrentOperation.Reset(false);   <------
end;
```

It would reset the command when you click on something but as a short-term fix it is probably better not having that feature than having access violations.

**Comment by AntoineGS** [comment]
So after way too much trial and error and trying to figure a way to get a notification when the opened file is closed I realized it was due to the down mouse event being used instead of up 😂
Let me know if you still have access violations with this new change!

**Comment by BvdLind** [comment]
Works perfectly, thank you!
